name: OrionBrowser
options:
  bundleIdPrefix: com.orion
  deploymentTarget:
    iOS: "17.0"
  developmentLanguage: en
  xcodeVersion: "15.0"
  generateEmptyDirectories: true
  groupSortPosition: top

settings:
  base:
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    SWIFT_VERSION: "5.9"
    ENABLE_USER_SCRIPT_SANDBOXING: false
    DEVELOPMENT_TEAM: ""
  configs:
    Debug:
      SWIFT_OPTIMIZATION_LEVEL: "-Onone"
      DEBUG_INFORMATION_FORMAT: "dwarf-with-dsym"
    Release:
      SWIFT_OPTIMIZATION_LEVEL: "-O"
      DEBUG_INFORMATION_FORMAT: "dwarf-with-dsym"

packages:
  Convex:
    url: https://github.com/get-convex/convex-swift
    from: "0.7.0"
  ClerkSDK:
    url: https://github.com/clerk/clerk-ios
    from: "0.71.0"

targets:
  OrionBrowser:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: OrionBrowser
        excludes:
          - "**/*.md"
          - "**/Package.swift"
          - "**/Tests/**"
    settings:
      base:
        INFOPLIST_FILE: OrionBrowser/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.orion.browser
        PRODUCT_NAME: "Orion Browser"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/Frameworks"
        CODE_SIGN_ENTITLEMENTS: OrionBrowser/OrionBrowser.entitlements
        TARGETED_DEVICE_FAMILY: "1,2"
        SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: true
        SUPPORTS_MACCATALYST: false
    dependencies:
      - package: Convex
        product: ConvexMobile
      - package: ClerkSDK
        product: Clerk
    info:
      path: OrionBrowser/Info.plist
      properties:
        CFBundleDisplayName: "Orion Browser"
        UILaunchStoryboardName: LaunchScreen
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        NSMicrophoneUsageDescription: "Orion uses the microphone for voice commands and audio capture."
        NSCameraUsageDescription: "Orion uses the camera for QR code scanning and video recording."
        NSLocationWhenInUseUsageDescription: "Orion uses your location to provide location-aware browsing suggestions."
        NSPhotoLibraryUsageDescription: "Orion needs access to your photo library to save screenshots and images."
        NSPhotoLibraryAddUsageDescription: "Orion needs permission to save images to your photo library."
        NSFaceIDUsageDescription: "Orion uses Face ID to securely authenticate and protect your data."
        NSSpeechRecognitionUsageDescription: "Orion uses speech recognition for voice commands."
        NSAppTransportSecurity:
          NSAllowsArbitraryLoads: true
          NSAllowsArbitraryLoadsInWebContent: true
        UIBackgroundModes:
          - audio
          - fetch
    entitlements:
      path: OrionBrowser/OrionBrowser.entitlements
      properties:
        com.apple.developer.associated-domains:
          - "applinks:orion.browser"
          - "webcredentials:orion.browser"
    preBuildScripts:
      - name: SwiftLint
        script: |
          if which swiftlint > /dev/null; then
            swiftlint
          else
            echo "warning: SwiftLint not installed"
          fi
        showEnvVars: false

  OrionBrowserTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: OrionBrowserTests
    dependencies:
      - target: OrionBrowser
    settings:
      TEST_HOST: "$(BUILT_PRODUCTS_DIR)/OrionBrowser.app/$(BUNDLE_EXECUTABLE_FOLDER_PATH)/OrionBrowser"

schemes:
  OrionBrowser:
    build:
      targets:
        OrionBrowser: all
        OrionBrowserTests: [test]
    run:
      config: Debug
      simulateLocation:
        allow: true
    test:
      config: Debug
      gatherCoverageData: true
      coverageTargets:
        - OrionBrowser
      targets:
        - OrionBrowserTests
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
